cargo-features = ["per-package-target"]

[package]
name = "adafruit-nrf52840-sense"
version = "0.1.0"
edition = "2018"
forced-target = "thumbv7em-none-eabihf"

[dependencies]
cortex-m = "0.6"
cortex-m-rt = "0.6"
nrf52840-hal = "0.14"
panic-halt = "0.2"
nb = "1.0.0"

adafruit-nrf52840-common = {path="../adafruit-nrf52840-common"}

bmp280-ehal = {git = "https://github.com/nnarain/bmp280.git", branch = "fix-configure-address"}
apds9960 = "0.1.0"

[dependencies.embedded-hal]
version = "0.2"
features = ["unproven"]
