cargo-features = ["per-package-target"]

[package]
name = "adafruit-nrf52840-common"
version = "0.2.0"
edition = "2018"
forced-target = "thumbv7em-none-eabihf"
publish = false

[dependencies]
nrf52840-hal = "0.14"

[dependencies.embedded-hal]
version = "0.2"
features = ["unproven"]
