[alias]
express-gdb = "run --package adafruit-nrf52840-express --target thumbv7em-none-eabihf"

sense-example-blink = "run --package adafruit-nrf52840-sense --target thumbv7em-none-eabihf --example blink"
sense-gdb = "run --package adafruit-nrf52840-sense --target thumbv7em-none-eabihf"



[target.'cfg(all(target_arch = "arm", target_os = "none"))']
runner = "arm-none-eabi-gdb -q -x nrf52.gdb"
rustflags = [
  "-C", "link-arg=-Tlink.x",
]
